{{- $root := . -}}
{{- $fullName := .Release.Name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "default-module.labels" . | nindent 4 }}
spec:
  {{- if .Values.minReadySeconds }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  {{- end }}
  # DeploymentSpec.paused - Ignored because no way of unsetting it
  {{- if .Values.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  {{- end }}
  {{- if .Values.replicas }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  # DeploymentSepc.revisionHistoryLimit - Ignored because empty and 0 are different
  selector:
    matchLabels:
      {{- include "default-module.selectorLabels" . | nindent 6 }}
  {{- if .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "default-module.selectorLabels" . | nindent 8 }}
        {{- if .Values.labels }}
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.annotations }}
        {{- range $key, $val := .Values.annotations }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
        {{- end }}
    spec:
      # PodSpec.activeDeadlineSeconds - Ignored because it only really applies to Jobs
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if hasKey .Values "automountServiceAccountToken" }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- end }}
      # PodSpec.dnsConfig - Ignored
      # PodSpec.dnsPolicy - Ignored
      # PodSpec.enableServiceLinks - Ignored because is set to true by default
      {{- if .Values.securityContext }}
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}
      {{- if .Values.hostIPC }}
      hostIPC: {{ .Values.hostIPC }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- end }}
      {{- if .Values.hostPID }}
      hostPID: {{ .Values.hostPID }}
      {{- end }}
      {{- if .Values.hostname }}
      hostname: {{ .Values.hostname }}
      {{- end }}
      # PodSpec.initContainers - Ignored for now because we need to solve the ordering problem first
      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      # PosSprec.os - Ignored because this is an alpha field and requires the IdentifyPodOS feature
      {{- if .Values.preemptionPolicy }}
      preemptionPolicy: {{ .Values.preemptionPolicy }}
      {{- end }}
      {{- if .Values.priority }}
      priority: {{ .Values.priority }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.readinessGates }}
      readinessGates:
        {{- toYaml .Values.readinessGates | nindent 8 }}
      {{- end }}
      {{- if .Values.overhead }}
      overhead:
        {{- toYaml .Values.overhead | nindent 8 }}
      {{- end }}
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      # PodSpec.serviceAccount - Ignored because it is officially deprecated
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      # Officially this is just an alias for the above
      serviceAccount: {{ .Values.serviceAccountName }}
      {{- end }}
      {{- if .Values.setHostnameAsFQDN }}
      setHostnameAsFQDN: {{ .Values.setHostnameAsFQDN }}
      {{- end }}
      {{- if .Values.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.shareProcessNamespace }}
      {{- end }}
      {{- if .Values.subdomain }}
      subdomain: {{ .Values.subdomain }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .Values.restartPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- end }}
      initContainers:
      {{ $initContainers := .Values.initContainers }}
      {{- range $i, $name :=  keys .Values.initContainers | sortAlpha }}
      {{ $data:= get $initContainers $name }}
        - name: {{ $name }}
          image: {{ $data.image | quote }}
          {{- if $data.imagePullPolicy }}
          imagePullPolicy: {{ $data.imagePullPolicy }} {{- /* From the docs: "One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise." */ -}}
          {{- end }}
          {{- if $data.liveness_probe }}
          livenessProbe:
            {{ include "default-module.containerProbe" $data.liveness_probe | nindent 12 }}
          {{- end }}
          {{- if $data.readiness_probe }}
          readinessProbe:
            {{ include "default-module.containerProbe" $data.readiness_probe | nindent 12 }}
          {{- end }}
          {{- if $data.startup_probe }}
          startupProbe:
            {{ include "default-module.containerProbe" $data.startup_probe | nindent 12 }}
          {{- end }}
          resources:
          {{- if $data.resources }}
            {{- toYaml $data.resources | nindent 12 }}
          {{- else }}
            {{- toYaml $root.Values.default_container_resources | nindent 12 }}
          {{- end }}
          {{- if $data.command }}
          command:
            {{- range $data.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if $data.args }}
          args:
            {{- range $data.args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if $data.lifecycle }}
          lifecycle:
            {{- if $data.lifecycle.preStop }}
            preStop:
            {{ include "default-module.lifecycleHandler" $data.lifecycle.preStop | nindent 14 }}
            {{- end }}
            {{- if $data.lifecycle.postStart }}
            postStart:
            {{ include "default-module.lifecycleHandler" $data.lifecycle.postStart | nindent 14 }}
            {{- end }}
          {{- end}}
          envFrom:
          - configMapRef:
              name: {{ $fullName }}-configmap-{{ $name }}
          {{- if $data.env }}
          env:
          {{- toYaml $data.env | nindent 10 }}
          {{- end }}
          {{- if $data.securityContext }}
          securityContext:
            {{- toYaml $data.securityContext | nindent 12 }}
          {{- end }}
          {{- if $data.stdin }}
          stdin: {{ $data.stdin }}
          {{- end }}
          {{- if $data.stdinOnce }}
          stdinOnce: {{ $data.stdinOnce }}
          {{- end }}
          {{- if $data.terminationMessagePath }}
          terminationMessagePath: {{ $data.terminationMessagePath | quote }}
          {{- end }}
          {{- if $data.terminationMessagePolicy }}
          terminationMessagePolicy: {{ $data.terminationMessagePolicy | quote }}
          {{- end }}
          {{- if $data.tty }}
          tty: {{ $data.tty }}
          {{- end }}
          {{- if $data.volumeDevices }}
          volumeDevices:
            {{- toYaml $data.volumeDevices | nindent 12 }}
          {{- end }}
          {{- if or $data.volumeMounts $data.volume_mounts }}
          volumeMounts:
          {{- if $data.volumeMounts }}
            {{- toYaml $data.volumeMounts | nindent 10 }}
          {{- end }}
          {{- if $data.volume_mounts }}
          {{- range $path, $data := $data.volume_mounts }}
          - name: {{ $data.id | quote }}
            mountPath: {{ $path | quote }}
            {{- if $data.sub_path }}
            subPath: {{ $data.sub_path | quote }}
            {{- end }}
            {{- if $data.read_only }}
            readOnly: {{ $data.read_only }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if $data.workingDir }}
          workingDir: {{ $data.workingDir | quote }}
          {{- end }}
      {{- end }}
      containers:
      {{- range $name, $data := .Values.containers }}
        - name: {{ $name }}
          image: {{ $data.image | quote }}
          {{- if $data.imagePullPolicy }}
          imagePullPolicy: {{ $data.imagePullPolicy }} {{- /* From the docs: "One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise." */ -}}
          {{- end }}
          {{- if $data.liveness_probe }}
          livenessProbe:
            {{ include "default-module.containerProbe" $data.liveness_probe | nindent 12 }}
          {{- end }}
          {{- if $data.readiness_probe }}
          readinessProbe:
            {{ include "default-module.containerProbe" $data.readiness_probe | nindent 12 }}
          {{- end }}
          {{- if $data.startup_probe }}
          startupProbe:
            {{ include "default-module.containerProbe" $data.startup_probe | nindent 12 }}
          {{- end }}
          resources:
          {{- if $data.resources }}
            {{- toYaml $data.resources | nindent 12 }}
          {{- else }}
            {{- toYaml $root.Values.default_container_resources | nindent 12 }}
          {{- end }}
          {{- if $data.command }}
          command:
            {{- range $data.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if $data.args }}
          args:
            {{- range $data.args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if $data.lifecycle }}
          lifecycle:
            {{- if $data.lifecycle.preStop }}
            preStop:
            {{ include "default-module.lifecycleHandler" $data.lifecycle.preStop | nindent 14 }}
            {{- end }}
            {{- if $data.lifecycle.postStart }}
            postStart:
            {{ include "default-module.lifecycleHandler" $data.lifecycle.postStart | nindent 14 }}
            {{- end }}
          {{- end}}
          envFrom:
          - configMapRef:
              name: {{ $fullName }}-configmap-{{ $name }}
          {{- if $data.env }}
          env:
          {{- toYaml $data.env | nindent 10 }}
          {{- end }}
          {{- if $data.securityContext }}
          securityContext:
            {{- toYaml $data.securityContext | nindent 12 }}
          {{- end }}
          {{- if $data.stdin }}
          stdin: {{ $data.stdin }}
          {{- end }}
          {{- if $data.stdinOnce }}
          stdinOnce: {{ $data.stdinOnce }}
          {{- end }}
          {{- if $data.terminationMessagePath }}
          terminationMessagePath: {{ $data.terminationMessagePath | quote }}
          {{- end }}
          {{- if $data.terminationMessagePolicy }}
          terminationMessagePolicy: {{ $data.terminationMessagePolicy | quote }}
          {{- end }}
          {{- if $data.tty }}
          tty: {{ $data.tty }}
          {{- end }}
          {{- if $data.volumeDevices }}
          volumeDevices:
            {{- toYaml $data.volumeDevices | nindent 12 }}
          {{- end }}
          {{- if or $data.volumeMounts $data.volume_mounts }}
          volumeMounts:
          {{- if $data.volumeMounts }}
            {{- toYaml $data.volumeMounts | nindent 10 }}
          {{- end }}
          {{- if $data.volume_mounts }}
          {{- range $path, $data := $data.volume_mounts }}
          - name: {{ $data.id | quote }}
            mountPath: {{ $path | quote }}
            {{- if $data.sub_path }}
            subPath: {{ $data.sub_path | quote }}
            {{- end }}
            {{- if $data.read_only }}
            readOnly: {{ $data.read_only }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if $data.workingDir }}
          workingDir: {{ $data.workingDir | quote }}
          {{- end }}
      {{- end }}
      {{- range .Values.extraContainers }}
        -
        {{- toYaml . | nindent 10 }}
      {{- end  }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 10 }}
    # Volumes part
    {{- if or .Values.volumes .Values.extraVolumes }}
      volumes:
    {{- end }}
      {{- range $name, $data := .Values.volumes }}
        - name: {{ $name }}
        {{ if eq $data.type "emptyDir" }}
          {{ if $data.source }}
          emptyDir:
            {{- toYaml $data.source | nindent 12 }}
          {{ else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{ if eq $data.type "projected" }}
          projected:
            sources:
              {{ if and $data.secret $data.secret.items }}
              - secret:
                  name: {{ $fullName }}-secrets
                  items:
                  {{- toYaml $data.secret.items | nindent 18 }}
              {{ end }}
              {{ if and $data.configMap $data.configMap.items }}
              - configMap:
                  name: {{ $fullName }}-configmap
                  items:
                  {{- toYaml $data.configMap.items | nindent 18 }}
              {{ end }}
        {{- end }}
      {{- end }}
      {{- range .Values.extraVolumes }}
        -
        {{- toYaml . | nindent 10 }}
      {{- end  }}
