{{- $root := . -}}
{{- $fullName := .Release.Name -}}
{{- range $name, $data := .Values.containers }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-configmap-{{ $name }}
  labels:
    {{- include "default-module.labels" $root | indent 4 }}
{{- if $data.variables }}
data:
  {{- with $data.variables }}
{{ toYaml . | indent 2 }}
  {{- end }}
{{ else }}
data: {}
{{- end }}
---
{{ end }}

{{- if .Values.variables -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-configmap
  labels:
    {{- include "default-module.labels" $root | indent 4 }}
data:
  {{- with .Values.variables }}
{{ toYaml . | indent 2 }}
  {{- end }}

{{- end }}