apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrds.humanitec.com
spec:
  group: humanitec.com
  names:
    plural: mycrds
    singular: mycrd
    kind: MyCRD
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                customField:
                  type: string
              required: ["customField"]
          required: ["spec"]
